"""empty message

Revision ID: 327308c951ed
Revises: c4300b8acd9f
Create Date: 2020-12-03 18:39:01.304029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327308c951ed'
down_revision = 'c4300b8acd9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('avr_salary', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'avr_salary')
    # ### end Alembic commands ###
